name: firebase_get_data
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:


  cupertino_icons: ^1.0.2
  #firebase_core: ^2.2.2
  firebase_database: ^7.1.1
  cloud_firestore: ^2.2.0
  firebase_storage: ^8.1.3
  cloud_functions: ^1.1.2
  flutter_screenutil: ^5.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
